title: 'AUTONOMED'
baseURL: 'https://autonomed.cl'
languageCode: 'es-cl'

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify

params:
  description: 'Investigación sobre medios digitales en Chile'
  
markup:
  goldmark:
    renderer:
      unsafe: true
