# Hugo configuration
baseURL: 'https://autonomed.cl'
title: 'AUTONOMED'
copyright: '© 2025 AUTONOMED - Ecosistemas de Medios Digitales Chile'

# Language
defaultContentLanguage: 'es'
languageCode: 'es-cl'

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

# Taxonomies
taxonomies:
  tag: tags
  category: categories
  author: authors

# Build
paginate: 10
enableEmoji: true
enableRobotsTXT: true

# Params
params:
  description: 'Investigación sobre ecosistemas de medios nativos digitales en Chile'
  email: 'contacto@autonomed.cl'
  twitter: 'autonomed_cl'
  
  # Address
  address:
    city: 'Santiago'
    country: 'Chile'
    country_code: 'CL'
