# Tema
appearance:
  theme_day: minimal
  theme_night: minimal
  font: native

# Contacto
contact_links:
  - icon: envelope
    icon_pack: fas
    name: Email
    link: 'mailto:contacto@autonomed.cl'
